// <auto-generated />
using System;
using BackEndCodeTrix.Src.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace App.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260905192653_FixAttendanceRelationship")]
    partial class FixAttendanceRelationship
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("AttendanceModel", b =>
                {
                    b.Property<int>("AttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LessonId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AttendanceId");

                    b.HasIndex("LessonId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentAttendances");
                });

            modelBuilder.Entity("BackEndCodeTrix.Src.Group.GroupModel", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CreatedByMentorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateOfCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("GroupId");

                    b.HasIndex("CreatedByMentorId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("BackEndCodeTrix.Src.LessonSchedule.LessonModel", b =>
                {
                    b.Property<int>("LessonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Classroom")
                        .HasColumnType("TEXT");

                    b.Property<int>("GroupId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LessonEnds")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LessonStarts")
                        .HasColumnType("TEXT");

                    b.Property<int>("LocationType")
                        .HasColumnType("INTEGER");

                    b.HasKey("LessonId");

                    b.HasIndex("GroupId");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("BackEndCodeTrix.Src.Tasks.StudentTaskModel", b =>
                {
                    b.Property<int>("StudentTaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MentorComment")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubmissionLink")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("TaskId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserModelUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("StudentTaskId");

                    b.HasIndex("StudentId");

                    b.HasIndex("TaskId");

                    b.HasIndex("UserModelUserId");

                    b.ToTable("StudentTasks");
                });

            modelBuilder.Entity("BackEndCodeTrix.Src.Tasks.TaskModel", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DeadLine")
                        .HasColumnType("TEXT");

                    b.Property<int>("GroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MentorComment")
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("TaskId");

                    b.HasIndex("GroupId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("BackEndCodeTrix.Src.Users.RoleModel", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("BackEndCodeTrix.Src.Users.UserModel", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("GroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserSurName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.HasIndex("GroupId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AttendanceModel", b =>
                {
                    b.HasOne("BackEndCodeTrix.Src.LessonSchedule.LessonModel", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEndCodeTrix.Src.Users.UserModel", "Student")
                        .WithMany("Attendances")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("BackEndCodeTrix.Src.Group.GroupModel", b =>
                {
                    b.HasOne("BackEndCodeTrix.Src.Users.UserModel", "CreatedByMentor")
                        .WithMany("CreatedGroups")
                        .HasForeignKey("CreatedByMentorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByMentor");
                });

            modelBuilder.Entity("BackEndCodeTrix.Src.LessonSchedule.LessonModel", b =>
                {
                    b.HasOne("BackEndCodeTrix.Src.Group.GroupModel", "Group")
                        .WithMany("Lessons")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("BackEndCodeTrix.Src.Tasks.StudentTaskModel", b =>
                {
                    b.HasOne("BackEndCodeTrix.Src.Users.UserModel", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BackEndCodeTrix.Src.Tasks.TaskModel", "Task")
                        .WithMany("StudentTasks")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEndCodeTrix.Src.Users.UserModel", null)
                        .WithMany("StudentTasks")
                        .HasForeignKey("UserModelUserId");

                    b.Navigation("Student");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("BackEndCodeTrix.Src.Tasks.TaskModel", b =>
                {
                    b.HasOne("BackEndCodeTrix.Src.Group.GroupModel", "Group")
                        .WithMany("Tasks")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("BackEndCodeTrix.Src.Users.UserModel", b =>
                {
                    b.HasOne("BackEndCodeTrix.Src.Group.GroupModel", "Group")
                        .WithMany("Students")
                        .HasForeignKey("GroupId");

                    b.HasOne("BackEndCodeTrix.Src.Users.RoleModel", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("BackEndCodeTrix.Src.Group.GroupModel", b =>
                {
                    b.Navigation("Lessons");

                    b.Navigation("Students");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("BackEndCodeTrix.Src.Tasks.TaskModel", b =>
                {
                    b.Navigation("StudentTasks");
                });

            modelBuilder.Entity("BackEndCodeTrix.Src.Users.RoleModel", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("BackEndCodeTrix.Src.Users.UserModel", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("CreatedGroups");

                    b.Navigation("StudentTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
